### ISSUE TITLE
Fails to set up 

### ISSUE THREAD

**Issue by bogdanioanliviu** [skagmo/ha_vwid#11]
This is the error message that i get. 
Tried remove component restart HA, add component restart HA same error allways. 

`2021-09-26 11:01:14 ERROR (MainThread) [homeassistant.components.sensor] vwid: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/config/custom_components/vwid/sensor.py", line 95, in async_update
    self._state = int(data['data']['batteryStatus']['currentSOC_pct'])
KeyError: 'batteryStatus'`

**Comment by bogdanioanliviu** [comment]
Fix by putting VIN in uppercase.
