### ISSUE TITLE
No device or entities appear after adding a car with 3.0 software

### ISSUE THREAD

**Issue by 7RST1** [skagmo/ha_vwid#28]
The car in question is a brand new iD.4 GTX registered in Norway. I suspect the user function to mess up the data path, but im not sure. All the data is visible in WeConnect iD as usual.

Error from log:

```
vwid: Error on device update!
Traceback (most recent call last):
File "/snap/home-assistant-snap/509/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity await entity.async_device_update(warning=False) 
File "/snap/home-assistant-snap/509/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 736, in async_device_update await task
File "/var/snap/home-assistant-snap/509/custom_components/vwid/sensor.py", line 95, in async_update self._state = int(data['data']['batteryStatus']['currentSOC_pct']) KeyError: 'batteryStatus'
```

**Comment by 7RST1** [comment]
Works again after reinstalling latest version and rebooting.. will open again if i face issues
