### ISSUE TITLE
Error on device update

### ISSUE THREAD

**Issue by erikosvaldsson** [skagmo/ha_vwid#29]
Since this morning the integration no longer updates properly and the log states:

```
vwid: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/config/custom_components/vwid/sensor.py", line 92, in async_update
    data = await self.api.get_status()
  File "/config/custom_components/vwid/libvwid.py", line 196, in get_status
    if await self.reconnect():
  File "/config/custom_components/vwid/libvwid.py", line 102, in reconnect
    (form, action) = self.password_form(await response.read())
  File "/config/custom_components/vwid/libvwid.py", line 43, in password_form
    (name, val) = line.strip().split(':', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

I have verified that the account works in the app, and I have tried restarting home assistant as well as removing and re-adding the integration. Still the same result.

**Comment by mauromognon** [comment]
same here!

**Comment by JaniAst** [comment]
same here.

**Comment by moikorg** [comment]
Unfortunately same here

**Comment by skagmo** [comment]
Thanks for the heads up. Got the same issue here when reloading the integration. Seems to be a slight change in the VW login page indeed. Try latest master, it should work now.

**Comment by mauromognon** [comment]
i've installed the latest version but i still have the problem

vwid: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/config/custom_components/vwid/sensor.py", line 92, in async_update
    data = await self.api.get_status()
  File "/config/custom_components/vwid/libvwid.py", line 198, in get_status
    if await self.reconnect():
  File "/config/custom_components/vwid/libvwid.py", line 104, in reconnect
    (form, action) = self.password_form(await response.read())
TypeError: cannot unpack non-iterable bool object

**Comment by moikorg** [comment]
I updated the `libvwid.py` file and after restart of hassio it is working as before. 
Thanks

**Comment by Hobjersgarden** [comment]
Ido de same: updated the libvwid.py file and after restart of hassio it is working as before.
Thanks

**Comment by JaniAst** [comment]
Working here too. Thanks

**Comment by mauromognon** [comment]
finally it works again, thanks a lot

**Comment by skagmo** [comment]
Good, thanks for testing!
