### ISSUE TITLE
Get status failed

### ISSUE THREAD

**Issue by moikorg** [skagmo/ha_vwid#31]
Hello

since yesterday (update of Home Assistant -> 2022.11.5) I get the following error at startup:

```
home-assistant   | 2022-12-06 07:36:24.113 ERROR (MainThread) [custom_components.vwid.libvwid] Get status failed
home-assistant   | 2022-12-06 07:36:24.120 ERROR (MainThread) [custom_components.vwid.sensor] Error retrieving data
home-assistant   | NoneType: None
```

Any idea what could be the cause?

**Comment by moikorg** [comment]
Just to add some more bug data that came a little bit later:

```
home-assistant   | 2022-12-06 07:46:26.018 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.wvgzzze2zmp030413_soc fails
home-assistant   | Traceback (most recent call last):
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
home-assistant   |     await self.async_device_update()
home-assistant   |   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
home-assistant   |     raise exc
home-assistant   |   File "/config/custom_components/vwid/sensor.py", line 92, in async_update
home-assistant   |     data = await self.api.get_status()
home-assistant   |   File "/config/custom_components/vwid/libvwid.py", line 198, in get_status
home-assistant   |     if await self.reconnect():
home-assistant   |   File "/config/custom_components/vwid/libvwid.py", line 90, in reconnect
home-assistant   |     response = await self.session.get(LOGIN_BASE + '/authorize', params=payload)
home-assistant   |   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 621, in _request
home-assistant   |     raise ValueError("Can redirect only to http or https")
home-assistant   | ValueError: Can redirect only to http or https
```

**Comment by skagmo** [comment]
Thanks for the notification. Closing as it duplicates #30
