### ISSUE TITLE
Non-2xx response error

### ISSUE THREAD

**Issue by JaniAst** [skagmo/ha_vwid#34]
Today started to come errors:

2023-02-27 19:36:40 ERROR (MainThread) [custom_components.vwid.libvwid] Non-2xx response
2023-02-27 19:36:40 ERROR (MainThread) [custom_components.vwid.libvwid] Reconnect failed
2023-02-27 19:36:40 ERROR (MainThread) [custom_components.vwid.sensor] Error retrieving data

**Comment by rleidner** [comment]
VW modified these URLs:
LOGIN_BASE = "https://emea.bff.cariad.digital/user-login/v1"
API_BASE = "https://emea.bff.cariad.digital/vehicle/v1"

**Comment by skagmo** [comment]
Thanks for the heads up @JaniAst and pointing in the right direction @rleidner. There seems to be some more changes than just the URLs, so I'll have to dig into later this week.

**Comment by skagmo** [comment]
Tested again this evening, and I simply had to go through the sign-in page again to agree to new terms... @rleidner your suggested URLs seems to be correct, thanks!

**Comment by JaniAst** [comment]
I get this error now. What I should do?

Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/vwid/libvwid.py:30
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 17:58:43 (1 occurrences)
Last logged: 17:58:43

vwid: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/config/custom_components/vwid/sensor.py", line 93, in async_update
    data = await self.api.get_status()
  File "/config/custom_components/vwid/libvwid.py", line 204, in get_status
    if await self.reconnect():
  File "/config/custom_components/vwid/libvwid.py", line 121, in reconnect
    (form, action) = self.form_from_response(await response.read())
  File "/config/custom_components/vwid/libvwid.py", line 30, in form_from_response
    return (form, page.forms[0].action)
IndexError: list index out of range

**Comment by skagmo** [comment]
@JaniAst I had the same issue and looked at the raw response to find out what was going on. Had to sign in again on myvolkswagen.net to accept updated terms even though I did it two weeks ago.

**Comment by JaniAst** [comment]
I thought that sign in with phone app would be enough. Now when I used browser it started to work ok. Thanks.

**Comment by skagmo** [comment]
👍
