### ISSUE TITLE
Icompatibilies with new versions of hoem assistant

### ISSUE THREAD

**Issue by harald-herberth** [skagmo/ha_vwid#47]
Great component, works great, like it very much.
I receive some erros though that might stop working once an update is made to new versions of HA beginning 2025.
Are there any plans to fix these issues and update ha_vwid?

DEVICE_CLASS_BATTERY was used from vwid, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.BATTERY instead, please report it to the author of the 'vwid' custom integration

HomeAssistantType was used from vwid, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'vwid' custom integration

Detected code that calls async_forward_entry_setup for integration vwid with title: Volkswagen ID custom and entry_id: 33b10b937b45bdc35760fe4fb75cefb1, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by skagmo** [comment]
Hi. Thanks for giving me a heads up. For some reason I didn't get these warnings even though I'm using the latest HA. Would appreciate if you can check if the warnings are gone now.

**Comment by harald-herberth** [comment]
Hi, sorry for installing and testing only as of today.
I run HA 2024.11.2 and vwid 0.1.1 7ad1a3d
Loading the components fails, her are the logs

2024-12-13 16:15:36.239 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'vwid' calls async_forward_entry_setup for integration, vwid with title: Volkswagen ID custom and entry_id: 33b10b937b45bdc35760fe4fb75cefb1, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/vwid/__init__.py, line 13: await hass.config_entries.async_forward_entry_setup(entry, "sensor"), please report it to the author of the 'vwid' custom integration
2024-12-13 16:15:39.137 WARNING (ImportExecutor_0) [homeassistant.const] DEVICE_CLASS_BATTERY was used from vwid, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.BATTERY instead, please report it to the author of the 'vwid' custom integration
2024-12-13 16:15:39.144 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from vwid, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'vwid' custom integration
2024-12-13 16:15:40.867 ERROR (MainThread) [homeassistant.components.sensor] vwid: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/vwid/sensor.py", line 94, in async_update
    data = await self.api.get_status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 204, in get_status
    if await self.reconnect():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 121, in reconnect
    (form, action) = self.form_from_response(await response.read())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 30, in form_from_response
    return (form, page.forms[0].action)
                  ~~~~~~~~~~^^^

**Comment by harald-herberth** [comment]
Had missed the fact that I apparently need to enter the configuration information again.
After doing so, I still get errors, some of which seen to be in loging into the VW site.
Nevertheless, async_forward_entry_setup and DEVICE_CLASS_BATTERY and HomeAssistantType stil stick around.

2024-12-13 18:49:50.300 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'vwid' calls async_forward_entry_setup for integration, vwid with title: Volkswagen ID custom and entry_id: d38a62dbd07059ae0ff9f1199668f451, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/vwid/__init__.py, line 13: await hass.config_entries.async_forward_entry_setup(entry, "sensor"), please report it to the author of the 'vwid' custom integration
2024-12-13 18:49:52.051 WARNING (ImportExecutor_0) [homeassistant.const] DEVICE_CLASS_BATTERY was used from vwid, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.BATTERY instead, please report it to the author of the 'vwid' custom integration
2024-12-13 18:49:52.058 WARNING (ImportExecutor_0) [homeassistant.helpers.typing] HomeAssistantType was used from vwid, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'vwid' custom integration
2024-12-13 18:49:53.331 ERROR (MainThread) [custom_components.vwid.libvwid] Email: Non-2xx response
2024-12-13 18:49:53.331 ERROR (MainThread) [custom_components.vwid.libvwid] Reconnect failed
2024-12-13 18:49:53.331 ERROR (MainThread) [custom_components.vwid.sensor] Error retrieving data
NoneType: None
2024-12-13 18:49:53.532 ERROR (MainThread) [custom_components.vwid.libvwid] Missing fields in response from VW API ('postAction')
2024-12-13 18:49:53.533 ERROR (MainThread) [homeassistant.components.sensor] vwid: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/vwid/sensor.py", line 94, in async_update
    data = await self.api.get_status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 204, in get_status
    if await self.reconnect():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 109, in reconnect
    (form, action) = self.password_form(await response.read())
    ^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable bool object
