### ISSUE TITLE
No devices or entries after HA 14.1 update

### ISSUE THREAD

**Issue by whistlebare** [skagmo/ha_vwid#49]
As the title suggests it looks like the integration has broke after the 14.1 update.  I tried deleting the integration and removing all files and folders from within HA and reinstalling but the same thing happens.
Any suggestions?
![Screenshot_20241223_105655_Home Assistant](https://github.com/user-attachments/assets/49b8d19f-8523-4563-91d6-07ea5c0a287a)

**Comment by AgentP38** [comment]
Same for me

**Comment by confucius78** [comment]
Have you had a look at accepting the t&c on the volkswagen site? I did that a while ago, but for some reason it broke again recently and I had to re-accept the terms for it to start working again

**Comment by AgentP38** [comment]
Yes I did that some weeks ago...

It broke yesterday after update

**Comment by whistlebare** [comment]
Yes i did it a few weeks ago too...been on the website and app and tried every option and there were no terms to accept.
  
Only happened after the update
  

  

  

  
  
  
  
  
>

**Comment by AgentP38** [comment]
I switched to the Volkswagen we connect ID integration... and if you change your country in the Vw profile. Save that back to your country then it's working

**Comment by whistlebare** [comment]
As if by magic the integration is now working...i did nothing so not sure what the fix was.    Merry xmas
  

  

  

  
  
  
  
  
>

**Comment by johnfredrik** [comment]
Also not getting any entities. Getting this error: 

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:737
integration: Sensor (documentation, issues)
First occurred: 16:48:32 (1 occurrences)
Last logged: 16:48:32

vwid: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 737, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/vwid/sensor.py", line 92, in async_update
    data = await self.api.get_status()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 204, in get_status
    if await self.reconnect():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 121, in reconnect
    (form, action) = self.form_from_response(await response.read())
                     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/vwid/libvwid.py", line 30, in form_from_response
    return (form, page.forms[0].action)
                  ~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by skagmo** [comment]
As @AgentP38 says you probably need to change country in your VW profile to something else, and then back to the correct country. I had to do this myself about three weeks ago to be able to log in again.

That issue aside, I've actually started using mitch-dc's integration (https://github.com/mitch-dc/volkswagen_we_connect_id) as it implements a lot more functionality like being able to control climate and adds device tracker entities. Unfortunately this means I will stop maintaining this project as I don't see any reason to keep it alive anymore. It might continue to work for a while, probably until the next time VW makes a major change in their API.

**Comment by whistlebare** [comment]
Many thanks I'll give this new integration a shot
  

  

  

  
  
  
  
  
>
