### ISSUE TITLE
Works in US?

### ISSUE THREAD

**Issue by gazpachoking** [skagmo/ha_vwid#7]
I see mention of 'we connect', which makes me wonder if this is supposed to work in the US or not (we have car-net app here, not we connect)?

This is the error I'm getting when enabling the component:
```python
2021-06-24 10:14:29 ERROR (MainThread) [homeassistant.components.sensor] vwid: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 550, in async_device_update
    await task
  File "/config/custom_components/vwid/sensor.py", line 92, in async_update
    data = await self.api.get_status()
  File "/config/custom_components/vwid/libvwid.py", line 156, in get_status
    if await self.reconnect():
  File "/config/custom_components/vwid/libvwid.py", line 87, in reconnect
    url = response.headers['Location']
KeyError: 'Location'
```

**Comment by skagmo** [comment]
Hi. Sorry, this will only work with We Connect ID.
